### ISSUE TITLE
disk module error

### ISSUE THREAD

**Issue by fuzebox1** [bcyran/fancy-motd#3]
Cool stuff, i like it. Bit slow on my pi zero but what to expect.
I get this error: 
`/home/pi/gits/fancy-motd/modules/32-disk: line 17: -1: substring expression < 0`
and it wont spit out disk graph. Also added the boot partition and it wont show numbers even.
Also the tmux module prints an error when no tmux is running.

**Comment by eh8** [comment]
￼the disk module has been rewritten, does this still occur?
