### ISSUE TITLE
Module "load" does not load

### ISSUE THREAD

**Issue by garret** [bcyran/fancy-motd#5]
I cannot understand why the load average module does not show up in my motd while I can see the other modules. I am using the latest raspberry pi os on (of course) a raspberry pi 4B. Is there a way to debug what could be the issue?

**Comment by eh8** [comment]
Try running the operative portions of the load module line by line, see if everything executed as expected

**Comment by garret** [comment]
I noticed that I get this error by giving this command: 

```
forfet@server:~ $ warning_threshold=$(bc -l <<< "$nproc * 0.9")
-bash: bc: command not found
forfet@server:~ $ 
```

Could that be the reason?

**Comment by VeKett** [comment]
Install 'bc' with whichever package manager your distribution provides.

**Comment by bcyran** [comment]
@garret Yup, that's exactly the reason. Install `bc` like @VeKett says and it will work.
I was going to put modules dependencies and a warning that modules will fail silently in the readme but I forgot. Definitely will do it.
