### ISSUE TITLE
Handle systemd timers

### ISSUE THREAD

**Issue by rhoriguchi** [bcyran/fancy-motd#9]
Currently, it only handles services, would be nice to somehow also handle timers.

https://github.com/bcyran/fancy-motd/blob/9ddea01cca5c93452440c46e2c4d6790e8b2c320/modules/33-services#L18-L19

As you can see it shows `Duck DNS` as down but the timer is up, the issue is that the service is triggered by a timer.

![image](https://user-images.githubusercontent.com/6047658/124932614-8375ef00-e003-11eb-9c84-b01c02bc7b55.png)
![image](https://user-images.githubusercontent.com/6047658/124933045-dbacf100-e003-11eb-9558-dc88913c6767.png)

I'm open to implementing something myself, I'm just not sure what's the best way to handle this.

**Comment by bcyran** [comment]
I think the most intuitive solution would be to just not append the `.service` and allow specifying any unit names. `systemctl show -p ActiveState --value {unit}` actually resolves to `{unit}.service` by default which is the same behavior like when using e.g. `systemctl status {unit}`. It also works correctly for other unit types like `{unit}.timer` or `{unit}.socket`.

We would only have to come up with different way than `systemctl list-unit-files` to check whether the unit exists at all.

**Comment by rhoriguchi** [comment]
> I think the most intuitive solution would be to just not append the `.service` and allow specifying any unit names. `systemctl show -p ActiveState --value {unit}` actually resolves to `{unit}.service` by default which is the same behavior like when using e.g. `systemctl status {unit}`. It also works correctly for other unit types like `{unit}.timer` or `{unit}.socket`.
> 
> We would only have to come up with different way than `systemctl list-unit-files` to check whether the unit exists at all.

Sadly that does not work, probably some if with some ands.

![image](https://user-images.githubusercontent.com/6047658/125139634-2f593080-e111-11eb-92ae-d99e3b4b8545.png)

**Comment by bcyran** [comment]
Sorry if I wasn't clear enough, I just meant that if we don't append `.service` then you could put this in config:
```shell
services["duckdns.timer"]="Duck DNS"
```

**Comment by bcyran** [comment]
@rhoriguchi Take a look at this: https://github.com/bcyran/fancy-motd/pull/10. I think it should work just fine if you specify a timer in your config like in the example above.

**Comment by bcyran** [comment]
Merged! Happy using and thanks for help.
